### PR TITLE
Add registration tests

### PR DESCRIPTION
**Pull request by Liberatys**
Implements the missing tests for #92

### CODE REVIEW

**Comment by Liberatys** [comment]
@dbrgn I hope the coverage is sufficient 👍🏻

**Comment by dbrgn** [comment]
The unit tests are nice, thanks! 👍🏻

Since the tests contain a lot of repetition of the same validation logic: Maybe adding [rstest](https://github.com/la10736/rstest) to this project would be a good idea. It allows you to parametrize tests (similar to pytest), so you can write a single, small test and run it with multiple inputs (and expected outputs). If you think this is cool, feel free to integrate rstest. If not, no problem either.

Having an integration test for the registration endpoint would be nice too, though. If you want to add such a test as well, take a look at the current auth tests for inspiration: https://github.com/dbrgn/flugbuech/blob/d7e5c56747edd6e4e84ce04eab093efb254adcb6/src/auth.rs#L267-L390 There's a test for the password change functionality. A similar test could be added for the registration: Send a request with the registration payload and ensure that a user is created in the database, and that an auth cookie is set on the response.

**Comment by dbrgn** [comment]
@Liberatys still interested in this? If not, just let me know, that would be OK too.

**Comment by dbrgn** [comment]
Replaced by #105. Thank you!

**Pull request closed without merging**
